Feature: A newly created bookmark is saved

    Scenario: bookmark is saved when a valid blog is created
        Given a valid blog with title "uusi" with url "http://www.somesite.org" is created
        When  ...
        Then  ...
